### ISSUE TITLE
decoder binary throws exception

### ISSUE THREAD

**Issue by ilbay** [s3rvac/cpp-bencoding#1]
Hi,

After building the library, when decoder binary is executed it displays this error:
./decoder ../../cpp-bencoding-src/sample/inputs/sample1.torrent 
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

I tested all samples provided in the library. All execution failed like this.
gcc version: 4.8.4
Ubuntu 14.04 x64
Kernel version: 3.16.0-77

**Comment by s3rvac** [comment]
Thanks for the report. I am afraid this is because [GCC 4.8 does not fully support `<regex>`](http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions). I have bumped the needed GCC version in the README from 4.8 to 4.9 (dbf7565). You will need to use GCC 4.9 or later.

**Comment by ghost** [comment]
i had same issue., this helped me.,

https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2

Thanks
